services:

  pizza-agents:
    build: 
      context: ./pizza-agents
      dockerfile: Dockerfile

    ports:
      - 8000:8000
    environment:
      - DMR_BASE_URL=${DMR_BASE_URL}
      - MODEL_RUNNER_MODEL=${PIZZA_MODEL_RUNNER_MODEL}
    #depends_on:
    #  - pizza-download-model

  hawaiian-agents:
    build: 
      context: ./hawaiian-agents
      dockerfile: Dockerfile

    ports:
      - 8001:8000
    environment:
      - DMR_BASE_URL=${DMR_BASE_URL}
      - MODEL_RUNNER_MODEL=${HAWAIIAN_MODEL_RUNNER_MODEL}
    #depends_on:
    #  - hawaiian-download-model

  mall-agents:
    build: 
      context: ./mall-agents
      dockerfile: Dockerfile
    ports:
      - 8002:8000
    environment:
      - DMR_BASE_URL=${DMR_BASE_URL}
      - MODEL_RUNNER_MODEL=${MALL_MODEL_RUNNER_MODEL}
    #depends_on:
    #  - mall-download-model

  rag-agents:
    build: 
      context: ./rag-agents
      dockerfile: Dockerfile
    ports:
      - 8003:8000
    environment:
      - DMR_BASE_URL=${DMR_BASE_URL}
      - MODEL_RUNNER_MODEL=${RAG_MODEL_RUNNER_MODEL}
      - MODEL_RUNNER_EMBEDDING_MODEL=${RAG_MODEL_RUNNER_EMBEDDING_MODEL}
    #depends_on:
    #  - rag-download-model
    #  - rag-download-embedding-model

  pizza-download-model:
    provider:
      type: model
      options:
        model: ${PIZZA_MODEL_RUNNER_MODEL}
