services:

  pizza-agents:
    build: 
      context: ./pizza-agents
      dockerfile: Dockerfile

    ports:
      - 8000:8000
    environment:
      - DMR_BASE_URL=${DMR_BASE_URL}
      - MODEL_RUNNER_MODEL=${PIZZA_MODEL_RUNNER_MODEL}
    depends_on:
      - pizza-download-model

  hawaiian-agents:
    build: 
      context: ./hawaiian-agents
      dockerfile: Dockerfile

    ports:
      - 8001:8000
    environment:
      - DMR_BASE_URL=${DMR_BASE_URL}
      - MODEL_RUNNER_MODEL=${HAWAIIAN_MODEL_RUNNER_MODEL}
    depends_on:
      - hawaiian-download-model

  mall-agents:
    build: 
      context: ./mall-agents
      dockerfile: Dockerfile
    ports:
      - 8002:8000
    environment:
      - DMR_BASE_URL=${DMR_BASE_URL}
      - MODEL_RUNNER_MODEL=${MALL_MODEL_RUNNER_MODEL}
    depends_on:
      - mall-download-model

  pizza-download-model:
    provider:
      type: model
      options:
        model: ${PIZZA_MODEL_RUNNER_MODEL}

  hawaiian-download-model:
    provider:
      type: model
      options:
        model: ${HAWAIIAN_MODEL_RUNNER_MODEL}

  mall-download-model:
    provider:
      type: model
      options:
        model: ${MALL_MODEL_RUNNER_MODEL}